public class allTheVariable {
    public final static String osago = "https://www.rgs.ru/auto/osago";
    public final static String iSee = "Понятно";
    public final static String title = "ОСАГО онлайн: калькулятор еОСАГО";
    public final static String wrong = "Не туда приперся";
    public final static String clicable = "//a[@class='action-item btn--basic']";
    public final static String frame = "//*[@id='RESOLUTE_INSURANCE']";
    public final static String noLicensePlate = "Нет номера";
    public final static String enginePower1 = "(//div[@class='input-group'])[1]";
    public final static String enginePower2 = "//*[@placeholder='Мощность двигателя']";
    public final static String hp = "л.с.";
    public final static String hP = "//div[text()='л.с.']";
    public final static String categoryB = "//div[contains(text(),'B')]";
    public final static String categoryb = "//div[text()='B']";
    public final static String passanger = "//div[contains(text(),'Легковой')]";
    public final static String passanger2 = "//div[text()='Легковой']";
    public final static String personal = "//div[contains(text(),'Личная')]";
    public final static String personal2 ="//div[text()='Личная']";
    public final static String stamp ="//div[contains(text(),'Марка')]";
    public final static String release ="//*[@placeholder='Год']";
    public final static String model ="//div[contains(text(),'Модель')]";
    public final static String noVIN ="//*[@for='content.object.data.noVin_custom_input']";
    public final static String notRegistered = "//*[@for='content.object.data.noGosNumber_custom_input']";
    public final static String chassis = "//div[contains(text(),'Шасси')]";
    public final static String chassis1 = "//div[text()='Шасси']";
    public final static String enterTheNumber = "//*[@placeholder='Укажите номер']";
    public final static String seriaPTS = "//*[@name='content.object.data.pts.seria']";
    public final static String numberPTS = "//*[@placeholder='Номер']";
    public final static String dataPTS = "//*[@placeholder='дд.мм.гггг']";
    public final static String term1yearC = "//div[contains(text(),'1 год')]";
    public final static String term1year = "//div[text()='1 год']";
    public final static String dataOsago = "//*[@name='content.object.data.periods[0].beginDate']";
    public final static String scroll1Year = "cрок страхования: 1 год";
    public final static String buttonNext1 = "//button[@class='btn btn-secondary']";
    public final static String surname = "//*[@name='content.insuredPerson.list[0].lastName']";
    public final static String limited = "Ограниченное";
    public final static String name = "//*[@name='content.insuredPerson.list[0].firstName']";
    public final static String middleName = "//*[@name='content.insuredPerson.list[0].middleName']";
    public final static String dateOfBirth = "//*[@name='content.insuredPerson.list[0].dob']";
    public final static String driverLincSeria = "//*[@name='content.insuredPerson.list[0].data.driverLicense.seria']";
    public final static String driverLincNumber ="//*[@name='content.insuredPerson.list[0].data.driverLicense.number']";
    public final static String driverLicData = "//*[@name='content.insuredPerson.list[0].data.experienceFrom']";
    public final static String buttonNo = "//button[@class='btn btn-outline-primary'][2]";
    public final static String buttonNext2 = "//*[@class='btn btn-secondary']";
    public final static String login = "//*[@placeholder='Логин (email)']";
    public final static String password = "//*[@placeholder='Пароль']";
    public final static String checkBox1 = "Даю ";
    public final static String buttonNext3 = "//*[@class='my-3 btn btn-secondary btn-block']";
    public final static String registAddress = "//*[@placeholder='Адрес регистрации']";
    public final static String buttonNext4 = "//*[@class='btn btn-secondary btn-block']";
    public final static String checkBox2 ="Страхователь подтверждает, ";
    public final static String buttonNext5 ="//*[@class='btn btn-secondary btn-block']";


}
